### ISSUE TITLE
Hey!

### ISSUE THREAD

**Issue by max-circlefade** [timwedde/banana-split#1]
Hey @timwedde  ! Saw you were working on MIDI using Python, that's great! I'm also doing a similar project, me developing a Rpi sequencer using a touchscreen. It also integrates AI generative stuff (magenta).

Would you like to get involved in it ?
Project is CircleFade, you can check our website :)
https://www.circlefade.com/

Thanks! Max

**Comment by timwedde** [comment]
Hey Max, this certainly looks like a very interesting project!
I've taken a glance at your website and from the looks of it you appear to be aiming for an area very similar to what I am active in, e.g. AI-driven multi-track compositions (albeit with a more hardware-focused angle). You even appear to be using a similar approach to what I explored in one of my own projects, [composer](https://github.com/timwedde/composer), which is pretty cool to see.
Since I am also a bit of a gearhead, especially when it comes to music gear (I'm a guitarist on the side), your project combines several of my main interests. As such I'd be very happy to learn more about what you've already achieved and what you're imagining for the future, and possibly even help out, should it turn out that some of my skills could be useful for this.

**Comment by max-circlefade** [comment]
Hey @timwedde, really happy to read that :)
I'dl love to go a bit deeper in the details of my project, do you have a FB or email I can write to ?
(preferably FB https://www.facebook.com/max.circlefade.3)
Many thanks, Max

**Comment by timwedde** [comment]
Hey Max, I have sent you a request on FB from tim.wedde.1
