### ISSUE TITLE
No output file

### ISSUE THREAD

**Issue by Moustiluigi** [timwedde/banana-split#3]
Hello,
I've been trying to make banana-split work for the last few hours and tried with several midi files but it always seem like there's no channels detected, so I always end up with no file at all. Is there any known reason why it won't work that you may know ?

![image](https://user-images.githubusercontent.com/42671335/116814408-210ef700-ab59-11eb-91f2-54a6df61334a.png)

Thanks, MLR.

**Comment by timwedde** [comment]
Could you perchance provide one or two of the MIDI files that are causing problems?
That way I can attempt to replicate and possibly fix this on my end.

**Comment by Moustiluigi** [comment]
Thank you for your quick answer.
Here are the few files i tried. song and song2 comes from vgmusic, MIDI_sample comes from a wikipedia article and test.mid was created with FL Studio and only has one channel. But none of them seem to work on my computer anyway. 

[songsource.zip](https://github.com/timwedde/banana-split/files/6411501/songsource.zip)

**Comment by timwedde** [comment]
Ah, i know what's up.
Looking at your screenshot from above, you're pointing the program at a single file.
The input it expects is a *folder* full of MIDI files.

Since this is a batch processing program, it normally works on multiple files at once.

This is also shown in the help text and the README:
`-i dir, --input dir   (required) The folder containing the input data`

If I point it at the songsource folder you uploaded above, it works just fine on my end.

**Comment by Moustiluigi** [comment]
I will probable need to rewrite the part of the script that scans files as I am not on a linux system but i'm pretty new to regex.
![image](https://user-images.githubusercontent.com/42671335/116816815-ccbd4480-ab63-11eb-9c56-66957202308e.png)
Or maybe i should modify it so that it only takes a single file as an input (the batch part of the process isn't what I am looking for).

**Comment by timwedde** [comment]
Well, this is first and foremost a batch processing script, so if you don't need it to batch process things, you may be better served with a different solution.
Either way, nothing's stopping you from just pointing it at a folder containing a single file, which will work just fine, so technically you can do single conversions like this, if needed.

You are right indeed that Windows systems will have some troubles with this script.
I never tested it on Windows since I don't use it personally and had no opportunity nor the incentive to.

The easiest fix for this would be to use WSL instead of the normal command line.
